config/routes.rb
Rails.application.routes.draw do
 

  resources :quests
  
  resources :users
  
  resources :advanced_searches

  
  get 'new_search' => 'quests#new_search'
  post 'new_search' => 'quests#index'
  
  get 'sessions/new'

  root 'main_static_pages#home'
   
  
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
 # delete 'logout'  => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  
  get 'profile' => 'users#show'

end

app/models/quest.rb
class Quest < ActiveRecord::Base
  belongs_to :quest_giver, :class_name => "User"   
  belongs_to :quester, :class_name => "User"
  validates :quest_giver, :presence => true
  
  validates :title, presence: true
  validates :description, presence: true

  validates :source, presence: true
  validates :destination, presence: true
  validates :reward, presence:true, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 10000 }

  def self.simple_search(search, current_user_obj)

    quests = default_search(current_user_obj)

    if search != nil && !search.empty?
      quests.where('title LIKE ?', "%#{search}%")

    else
      quests

    
    end
  end

  def self.search(search_options, current_user_obj)

    quests = default_search(current_user_obj)

    quests = quests.where('title LIKE ?', "%#{search_options[:title]}%") if search_options[:title].present?
    quests = quests.where('source LIKE ?', "%#{search_options[:source]}%") if search_options[:source].present?
    quests = quests.where('destination LIKE ?', "%#{search_options[:destination]}%") if search_options[:destination].present?
    quests = quests.where('reward >= ?', search_options[:reward_min]) if search_options[:reward_min].present?
    quests = quests.where('reward <= ?', search_options[:reward_max]) if search_options[:reward_max].present?
    quests

  end

  private

  def self.default_search(current_user_obj)
    quests = Quest.where.not(completed: true)
    quests = quests.where(quester_id: nil)
  #  quests = quests.where('(quest_giver_id IS ?) OR (quest_giver_id != ?)', nil, current_user_obj.id)
    quests = quests.where.not(quest_giver_id: current_user_obj.id)
    quests
  end

end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :require_login
  helper_method :sort_column, :sort_direction

  

  # GET /quests
  # GET /quests.json
  def index
    # query = params[:q]
    # query ||= {}

    # @search = Quest.search(query.merge({ quester_id_null: 1, quest_giver_id_not_eq: current_user.id, completed_eq: false}))
    
    # @quests = @search.result.paginate(:page => params[:page], :per_page => 10)
    
    # @search = Quest.search(params[:q])
    # @search.build_condition if @search.conditions.empty?

    if params.has_key?(:session)
      
        if sort_column != 'quest_giver_id'
          @quests = Quest.search(params[:session], current_user).order(sort_column + " " + sort_direction)
    .paginate(:page => params[:page], :per_page => 10)
        else
          @quests = Quest.search(params[:session], current_user).joins("JOIN users ON users.id = quests.quest_giver_id").order("users.name " + sort_direction)
    .paginate(:page => params[:page], :per_page => 10)
        end

    else

      if sort_column != 'quest_giver_id'
        @quests = Quest.simple_search(params[:search], current_user).order(sort_column + " " + sort_direction)
    .paginate(:page => params[:page], :per_page => 10)
      else
        @quests = Quest.simple_search(params[:search], current_user).joins("JOIN users ON users.id = quests.quest_giver_id").order("users.name " + sort_direction)
    .paginate(:page => params[:page], :per_page => 10)

      end
    end

  end

  def update
    @quest = Quest.find(params[:id])
  
    redirect_to quest_path(@quest) unless !@quest.completed

    fields = update_quest_params
    if fields[:quester_id] && (Integer(fields[:quester_id]) == current_user.id)
      @quest.quester = current_user
    end

    if fields[:completed]
      @quest.completed = true
    end

    @quest.save

    redirect_to quest_path(@quest)
  end

  # GET /quests/1
  # GET /quests/1.json
  def show
    @quest = Quest.find(params[:id])
  end

  # GET /quests/new
  def new
    @quest = Quest.new
  end

  def create
    @quest = Quest.new(new_quest_params)
    @quest.quest_giver = current_user
    if @quest.save
      redirect_to profile_path
    else
      render 'new'
    end
  end

  def new_search

  end

  private
  def new_quest_params
    params.require(:quest).permit(:title, :description, :source, :destination, :reward)
  end

  def update_quest_params
    params.require(:quest).permit(:quester_id, :completed)
  end


  
  def sort_column
    Quest.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
 
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/_condition_fields.html.erb
<div class="field">
  <div class="row">
    <div class="col-md-2">
    <%= f.attribute_fields  do |a| %>
      <%= a.attribute_select associations: [:user] %>
    <% end %>
    </div>

    <div class="col-md-2">
    <%= f.predicate_select %>
    </div>

    <div class="col-md-4">
    <%= f.value_fields do |v| %>
      <%= v.text_field :value %>
    <% end %>
    </div>

    <div class="col-md-4">
    <%= link_to "remove", '#', class: "remove_fields" %>
    </div>
    
  </div>
</div>

app/views/quests/_form.html.erb
<%= form_for(@quest) do |f| %>
  <% if @quest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quest.errors.count, "error") %> prohibited this quest from being saved:</h2>

      <ul>
      <% @quest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :reward %><br>
    <%= f.text_field :reward %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quests/_quest.html.erb
<li id="quest-<%= quest.id %>">

  
  <span class="title"><%= quest.id.to_s + ": " + quest.title %></span>
  <span class="content">Given by: <%= quest.quest_giver == nil ? 
  "System" : quest.quest_giver.name %> </span>
  <span class="content">Accepted by: <%= quest.quester == nil ? 
  "Nobody" : quest.quester.name %> </span>
  <span class="content">Reward: <%= quest.reward %> </span>
  <span class="content">From <%= quest.source %> to <%= quest.destination %>
  </span>
  
  <span class="timestamp">
    Posted <%= time_ago_in_words(quest.created_at) %> ago.
  </span>
</li>

app/views/quests/index.html.erb
<% provide(:title, 'Quests') %>
<h1>Quests</h1>

<%= form_tag quests_path, :method => 'get', :class => "form-horizontal" do %>

     <%= hidden_field_tag :direction, params[:direction] %>
     <%= hidden_field_tag :sort, params[:sort] %>
     
      <div class="col-xs-4">
        <div class="input-group">
          <%= text_field_tag :search, params[:search], class: "form-control", 
          placeholder: "Search in title" %>
         
          <span class="input-group-btn">
          <%= submit_tag "Search", :name => nil, class: "btn btn-primary"%>
          </span>


        </div>

     

        <%= link_to "Advanced Search", new_search_path, class: "top-buffer" %>
       

      </div>

 
<% end %>
 
 


<%= render 'shared/quests_table' %>

app/views/quests/new.html.erb
<% content_for :head do %>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
        #map-canvas1, #map-canvas2 {
            width: 550px;
            height: 300px;
            margin-top: 20px;
            padding: 14px;
        }
    </style>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false&amp;libraries=places"></script>

<% end %>

<h1>Post a new Quest</h1>
  <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@quest) do |f| %>

      <%= render 'shared/error_messages' %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, size: '60x8', class: 'form-control' %>

      <%= f.label :source %>
      <%= f.text_field :source , class: 'form-control'%>
        <div id="map-canvas1"></div>

      <%= f.label :destination %>
      <%= f.text_field :destination , class: 'form-control'%>
        <div id="map-canvas2"></div>

        <%= f.label :reward %>
      <%= f.text_field :reward , class: 'form-control'%>
        <br>
      <%= f.submit "Create Quest", class: "btn btn-primary" %>
    <% end %>
    <script>initialize()</script>
  </div>
</div>
<script type="text/javascript">
    //Autocomplete variables
    var input1 = document.getElementById('quest_source');
    var input2 = document.getElementById('quest_destination');
    var place1, place2;
    var autocomplete1 = new google.maps.places.Autocomplete(input1);
    var autocomplete2 = new google.maps.places.Autocomplete(input2);

    //Google Map variables
    var map1, map2;
    var marker1, marker2;

    //Add listener to detect autocomplete selection
    google.maps.event.addListener(autocomplete1, 'place_changed', function () {
        place1 = autocomplete1.getPlace();
        var newlatlong1 = new google.maps.LatLng(place1.geometry.location.lat(),place1.geometry.location.lng());
        map1.setCenter(newlatlong1);
        marker1.setPosition(newlatlong1);
        map1.setZoom(14);
    });
    google.maps.event.addListener(autocomplete2, 'place_changed', function () {
        place2 = autocomplete2.getPlace();
        var newlatlong2 = new google.maps.LatLng(place2.geometry.location.lat(),place2.geometry.location.lng());
        map2.setCenter(newlatlong2);
        marker2.setPosition(newlatlong2);
        map2.setZoom(14);
    });

    // Set the centers of the map upon receiving current geolocation
    function setCenter(position) {
        map1.setCenter(new google.maps.LatLng(position.coords.latitude, position.coords.longitude));
        map1.setZoom(12);
        map2.setCenter(new google.maps.LatLng(position.coords.latitude, position.coords.longitude));
        map2.setZoom(12);
    }

    //Reset the input box on click
    input1.addEventListener('click', function(){
        input1.value = "";
    });
    input2.addEventListener('click', function(){
        input2.value = "";
    });



    function initialize() {
        var myLatlng1 = new google.maps.LatLng(0,0);
        var myLatlng2 = new google.maps.LatLng(0,0);
        var mapOptions = {
            zoom: 1,
            center: myLatlng1
        }
        map1 = new google.maps.Map(document.getElementById('map-canvas1'), mapOptions);
        map2 = new google.maps.Map(document.getElementById('map-canvas2'), mapOptions);

        marker1 = new google.maps.Marker({
            position: myLatlng1,
            map: map1,
            title: 'Source map'
        });
        marker2 = new google.maps.Marker({
            position: myLatlng2,
            map: map2,
            title: 'Destination map'
        });

        navigator.geolocation.getCurrentPosition(setCenter);
    }

    google.maps.event.addDomListener(window, 'load', initialize);

</script>

app/views/quests/new_search.html.erb
<h1>Advanced Search</h1>


    <%= form_for(:session, :url => quests_path, :method => :get, :html => {:class => "form-horizontal"}) do |f| %>

 
      <div class="form-group">
        <%= f.label :title, "Title contains:", class: 'control-label col-xs-2'  %>
        <div class="col-xs-4">
            <%= f.text_field :title, class: 'form-control' %>
        </div>
      </div>


      <div class="form-group">
        <%= f.label :source, "Source contains:", class: 'control-label col-xs-2'  %>
        <div class="col-xs-4">
            <%= f.text_field :source, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :destination, "Destination contains:", class: 'control-label col-xs-2'  %>
        <div class="col-xs-4">
            <%= f.text_field :destination, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :reward_min, "Reward range:", class: 'control-label col-xs-2'%>
        <div class="col-xs-2">
          <div class="input-group">
            <span class="input-group-addon">Min</span>
            <%= f.text_field :reward_min, class: 'form-control' %>
          </div>
        </div>
      
        <div class="col-xs-2">
          <div class="input-group">
            <span class="input-group-addon">Max</span>
            <%= f.text_field :reward_max, class: 'form-control' %>
          </div>
        </div>
      </div>



      <div class="form-group">
        <div class="col-xs-offset-2 col-xs-2">
        <%= f.submit "Search", class: "btn btn-primary" %>
        </div>
      </div>
  

    <% end %>

app/views/quests/show.html.erb
<h1><%= @quest.title %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div><p class="quest_description"><%= @quest.description %></p></div>
      <div>
	<p>Reward: <%= @quest.reward %></p>
	<p>Quest Giver: <%= @quest.quest_giver ? @quest.quest_giver.name
        : "System" %></p>
      </div>
      <% if @quest.completed %>
      <h2>Quest complete!</h2>
      <% else %>
      <% if @quest.quester && @quest.quester != current_user %>
      <p>Someone else has already accepted this quest</p>
      <% elsif @quest.quester %>
      <!-- TODO -->
      <%= form_for @quest do |f| %>
      <%= f.hidden_field :completed, value: "true" %>
      <%= f.submit "Complete Quest", class: "btn btn-success" %>
      <% end %>	
      <% else %>
      <div>
	  <%= form_for @quest do |f| %>
	  <%= f.hidden_field :quester_id, value: current_user.id %>
	  <%= f.submit "Accept Quest", class: "btn btn-primary" %>
	  <% end %>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>