config/routes.rb
Rails.application.routes.draw do
 

  resources :quests
  
  resources :users
  
  resources :advanced_searches

  
  get 'new_search' => 'quests#new_search'
  post 'new_search' => 'quests#index'
  
  get 'sessions/new'

  root 'main_static_pages#home'
   
  
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
 # delete 'logout'  => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  
  get 'profile' => 'users#show'

end

app/models/user.rb
class User < ActiveRecord::Base

 # attr_accessor :name, :email
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX }, 
    uniqueness: {case_sensitive: false }
  validates :password, length: { minimum: 6 }

  has_secure_password

  has_many :posted_quests, :class_name => "Quest", :foreign_key => "quest_giver_id"
  has_many :quests, :class_name => "Quest", :foreign_key => "quester_id"

  # def initialize(attributes = {})
  #   @name  = attributes[:name]
  #   @email = attributes[:email]
  # end

  # def formatted_email
  #   "#{@name} <#{@email}>"
  # end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]
  def new
    @user = User.new
  end

  def show
    @user = current_user
    @posted_quests = Quest.where(quest_giver: @user)
    @accepted_quests = Quest.where(quester: @user, completed: false)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # Handle a successful save.
      log_in @user
      flash[:success] = "Welcome to " + Constant.app_name
      redirect_to profile_path
    else
      render 'new'
    end
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password , class: 'form-control'%>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<div class="container-fluid">
<div class="row">
  <aside class="col-md-6">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
        <br><br>User ID : <%= @user.id %>
      </h1>
    </section>
</aside>
</div>
<div class="row">
  <div class="col-md-6">
    <section class="posted_quests">
      <h2>Posted Quests</h2>
      <% if @posted_quests.any? %>
      <ul>
  <% @posted_quests.each do |quest| %>
  <li><a href="<%= quest_url(quest) %>"><%= quest.title %></a></li>
  <% end %>
      </ul>
      <% else %>
      <span> None... </span>
      <% end %>

      <a href="<%= new_quest_path %>" class="btn btn-primary">Post a new quest</a>
    </section>
  </div>

  <div class="col-md-6">
    <section class="accepted_quests">
      <h2>Active Quests</h2>
      <% if @accepted_quests.any? %>
      <ul>
  <% @accepted_quests.each do |quest| %>
  <li><a href="<%= quest_url(quest) %>"><%= quest.title %></a></li>
  <% end %>
      </ul>
      <% else %>
      <span> None... </span>
      <% end %>
      <a href="<%= quests_path %>" class="btn btn-primary">Find a quest!</a>
    </section>
  </div>
</div>
</div>
</html>