config/routes.rb
Rails.application.routes.draw do
 

  resources :quests
  
  resources :users
  
  resources :advanced_searches

  
  get 'new_search' => 'quests#new_search'
  post 'new_search' => 'quests#index'
  
  get 'sessions/new'

  root 'main_static_pages#home'
   
  
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
 # delete 'logout'  => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  
  get 'profile' => 'users#show'

end

app/controllers/main_static_pages_controller.rb
class MainStaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
  def quests
  
  end
  
end

app/helpers/main_static_pages_helper.rb
module MainStaticPagesHelper
end

app/views/main_static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>
<p>About this web application</p>

app/views/main_static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
   Contact inforamtion
</p>

app/views/main_static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help</h1>
<p>Documentation on how to use <%= Constant.app_name %></p>

app/views/main_static_pages/home.html.erb
<div class="center jumbotron">

  <h1>Welcome to use <%= Constant.app_name%> !</h1>

  <h3>
    The world is like a role-playing game..
  </h3>

  <% if !logged_in? %>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

app/views/main_static_pages/quests.html.erb
<% provide(:title, 'Quests') %>
<h1>Quests</h1>

<!--
<div class="row">
  
  <div class="input-group" >

    <%= form_tag quests_path, :method => 'get', :class => "form-inline" do %>
     
      <%= text_field_tag :search, params[:search] %>
     
      <%= submit_tag "Search", :name => nil, class: "btn btn-primary"%>
    
    <% end %>
  </div>
 
</div>
-->

<%= search_form_for @search do |f| %>
  <div class = "field">
    <%= f.label :title_cont, "Title contains" %>
    <%= f.text_field :title_cont %>
  </div>
  <div class = "actions"><%= f.submit "Search" %></div>
  
<% end %>


<div class="row">
  <div class="col-md-8">
    <% if @quests.any? %>
      <h3>Quests (<%= @quests.count %>)</h3>



      <ol class="quests">
        <%= render @quests %>
      </ol>
      <%= will_paginate @quests %>
    <% end %>
  </div>
</div>