config/routes.rb
Rails.application.routes.draw do
 

  resources :quests
  
  resources :users
  
  resources :advanced_searches

  
  get 'new_search' => 'quests#new_search'
  post 'new_search' => 'quests#index'
  
  get 'sessions/new'

  root 'main_static_pages#home'
   
  
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
 # delete 'logout'  => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  
  get 'profile' => 'users#show'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to Constant.app_name, root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav pull-right">
            <% if logged_in? %>

            <li><%= link_to "Quests", quests_path, id: "logo_s" %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", profile_path %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "get" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
        
          </ul>
        </nav>
      </div>
 </header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %> </title>

  <link href="http://cdn.bootcss.com/bootstrap-table/1.3.0/bootstrap-table.min.css" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

  <%= yield :head %>
</head>
<body>

    <%= render 'layouts/header' %>
    <div class="container">

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <%= yield %>

      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
      
      
    </div>

  <script src="http://cdn.bootcss.com/bootstrap-table/1.3.0/bootstrap-table.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap-table/1.3.0/locale/bootstrap-table-en-US.min.js"></script>

</body>
</html>